export const CATEGORY_DISPLAY_START = 'CATEGORY_DISPLAY_START';
export const CATEGORY_DISPLAY_END = 'CATEGORY_DISPLAY_END';
export const CATEGORY_DISPLAY_SUCCESS = 'CATEGORY_DISPLAY_SUCCESS';
export const CATEGORY_DISPLAY_FAILURE = 'CATEGORY_DISPLAY_FAILURE';

export const CATEGORY_CREATE_START = 'CATEGORY_CREATE_START';
export const CATEGORY_CREATE_END = 'CATEGORY_CREATE_END';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAILURE = 'CATEGORY_CREATE_FAILURE';

export const CATEGORY_DELETE_START = 'CATEGORY_DELETE_START';
export const CATEGORY_DELETE_END = 'CATEGORY_DELETE_END';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILURE = 'CATEGORY_DELETE_FAILURE';