export const PROVINCE_DISPLAY_START = 'PROVINCE_DISPLAY_START';
export const PROVINCE_DISPLAY_END = 'PROVINCE_DISPLAY_END';
export const PROVINCE_DISPLAY_SUCCESS = 'PROVINCE_DISPLAY_SUCCESS';
export const PROVINCE_DISPLAY_FAILURE = 'PROVINCE_DISPLAY_FAILURE';

export const DISTRICT_DISPLAY_START = 'DISTRICT_DISPLAY_START';
export const DISTRICT_DISPLAY_END = 'DISTRICT_DISPLAY_END';
export const DISTRICT_DISPLAY_SUCCESS = 'DISTRICT_DISPLAY_SUCCESS';
export const DISTRICT_DISPLAY_FAILURE = 'DISTRICT_DISPLAY_FAILURE';

export const SECTOR_DISPLAY_START = 'SECTOR_DISPLAY_START';
export const SECTOR_DISPLAY_END = 'SECTOR_DISPLAY_END';
export const SECTOR_DISPLAY_SUCCESS = 'SECTOR_DISPLAY_SUCCESS';
export const SECTOR_DISPLAY_FAILURE = 'SECTOR_DISPLAY_FAILURE';