export const MARKET_DISPLAY_START = 'MARKET_DISPLAY_START';
export const MARKET_DISPLAY_END = 'MARKET_DISPLAY_END';
export const MARKET_DISPLAY_SUCCESS = 'MARKET_DISPLAY_SUCCESS';
export const MARKET_DISPLAY_FAILURE = 'MARKET_DISPLAY_FAILURE';

export const MARKET_CREATE_START = 'MARKET_CREATE_START';
export const MARKET_CREATE_END = 'MARKET_CREATE_END';
export const MARKET_CREATE_SUCCESS = 'MARKET_CREATE_SUCCESS';
export const MARKET_CREATE_FAILURE = 'MARKET_CREATE_FAILURE';

export const MARKET_DELETE_START = 'MARKET_DELETE_START';
export const MARKET_DELETE_END = 'MARKET_DELETE_END';
export const MARKET_DELETE_SUCCESS = 'MARKET_DELETE_SUCCESS';
export const MARKET_DELETE_FAILURE = 'MARKET_DELETE_FAILURE';

export const MARKET_UPDATE_START = 'MARKET_UPDATE_START';
export const MARKET_UPDATE_END = 'MARKET_UPDATE_END';
export const MARKET_UPDATE_SUCCESS = 'MARKET_UPDATE_SUCCESS';
export const MARKET_UPDATE_FAILURE = 'MARKET_UPDATE_FAILURE';
