export const ORDER_PRODUCT_START = 'ORDER_PRODUCT_START';
export const ORDER_PRODUCT_END = 'ORDER_PRODUCT_END';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAILURE = 'ORDER_PRODUCT_FAILURE';

export const CLIENT_ORDERS_START = 'CLIENT_ORDERS_START';
export const CLIENT_ORDERS_END = 'CLIENT_ORDERS_END';
export const CLIENT_ORDERS_SUCCESS = 'CLIENT_ORDERS_SUCCESS';
export const CLIENT_ORDERS_FAILURE = 'CLIENT_ORDERS_FAILURE';

export const DISPLAY_ORDERS_START = 'DISPLAY_ORDERS_START';
export const DISPLAY_ORDERS_END = 'DISPLAY_ORDERS_END';
export const DISPLAY_ORDERS_SUCCESS = 'DISPLAY_ORDERS_SUCCESS';
export const DISPLAY_ORDERS_FAILURE = 'DISPLAY_ORDERS_FAILURE';

export const SEARCH_ORDER_START = 'SEARCH_ORDER_START';
export const SEARCH_ORDER_END = 'SEARCH_ORDER_END';
export const SEARCH_ORDER_SUCCESS = 'SEARCH_ORDER_SUCCESS';
export const SEARCH_ORDER_FAILURE = 'SEARCH_ORDER_FAILURE';

export const CANCEL_ORDER_START = 'CANCEL_ORDER_START';
export const CANCEL_ORDER_END = 'CANCEL_ORDER_END';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

export const DELIVER_ORDER_START = 'DELIVER_ORDER_START';
export const DELIVER_ORDER_END = 'DELIVER_ORDER_END';
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS';
export const DELIVER_ORDER_FAILURE = 'DELIVER_ORDER_FAILURE';
