export const ORDER_PRODUCT_START = 'ORDER_PRODUCT_START';
export const ORDER_PRODUCT_END = 'ORDER_PRODUCT_END';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAILURE = 'ORDER_PRODUCT_FAILURE';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_END = 'USER_LOGIN_END';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
