export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
export const CREATE_PRODUCT_END = 'CREATE_PRODUCT_END';

export const DISPLAY_PRODUCT_START = 'DISPLAY_PRODUCT_START';
export const DISPLAY_PRODUCT_SUCCESS = 'DISPLAY_PRODUCT_SUCCESS';
export const DISPLAY_PRODUCT_FAILURE = 'DISPLAY_PRODUCT_FAILURE';
export const DISPLAY_PRODUCT_END = 'DISPLAY_PRODUCT_END';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_END = 'UPDATE_PRODUCT_END';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';
export const DELETE_PRODUCT_END = 'DELETE_PRODUCT_END';
