export const USER_SEARCH_START = 'USER_SEARCH_START';
export const USER_SEARCH_END = 'USER_SEARCH_END';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE';
