export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_END = 'USER_SIGNUP_END';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_END = 'USER_LOGIN_END';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_END = 'USER_LOGOUT_END';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_DISPLAY_START = 'USER_DISPLAY_START';
export const USER_DISPLAY_END = 'USER_DISPLAY_END';
export const USER_DISPLAY_SUCCESS = 'USER_DISPLAY_SUCCESS';
export const USER_DISPLAY_FAILURE = 'USER_DISPLAY_FAILURE';

export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_END = 'USER_UPDATE_END';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
